
services:
    db:
        image: postgres:16-alpine
        container_name: main_db
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        # Mengatur performa sesuai RAM 2GB (Shared Buffers 25% dari Limit)
        command: ["postgres", "-c", "shared_buffers=256MB", "-c", "max_connections=100"]
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - main_net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
              limits:
                memory: "800M"

    redis:
        image: redis:7-alpine
        container_name: main_redis
        restart: always
        command: ["redis-server", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
        networks:
            - main_net
        deploy:
            resources:
                limits:
                    memory: 200M

    migration:
        build: ghcr.io/muhammadpauzi/bun-api:latest
        pull_policy: always  # Memastikan Docker selalu mengecek versi terbaru di GHCR
        container_name: bun_migration
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
        # Hanya jalankan script migrasi lalu mati (exit)
        command: ["bun", "run", "src/migrate.ts"]
        networks:
            - main_net

    api:
        build: ghcr.io/muhammadpauzi/bun-api:latest
        pull_policy: always  # Memastikan Docker selalu mengecek versi terbaru di GHCR
        container_name: bun_api
        restart: always
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
            migration:
                condition: service_completed_successfully
        networks:
            - main_net
        stop_grace_period: 30s
        deploy:
            resources:
                limits:
                    memory: 300M

    worker:
        build: ghcr.io/muhammadpauzi/bun-api:latest
        pull_policy: always  # Memastikan Docker selalu mengecek versi terbaru di GHCR
        container_name: bun_worker
        restart: always
        command: ["bun", "run", "src/worker.ts"] # timpa
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
        networks:
            - main_net
        stop_grace_period: 2m  # Memberi waktu ekstra bagi worker untuk beres-beres
        deploy:
            resources:
                limits:
                    memory: 200M

    nginx:
        image: nginx
        container_name: main_proxy
        restart: always
        ports:
            - "80:80"
           #  - "443:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - api
        networks:
            - main_net
        deploy:
            resources:
                limits:
                    memory: 100M

networks:
  main_net:
    driver: bridge

volumes:
  postgres_data: